---

name: Docker

on:
  push:
    branches:
      - main

env:
  APP_NAME: release-dash
  DOCKER_BUILD_TARGET: run
  DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
  DOCKER_REPO_URL: docker.pkg.github.com
  DOCKER_REPOSITORY: lobsterdore
  DOCKER_USER: "${{ github.actor }}"

jobs:

  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout out repo
        uses: actions/checkout@v2
        with:
          path: release-dash

      - name: Build  and test image
        run: |
          cd $GITHUB_WORKSPACE/$APP_NAME
          make docker_test

      - name: Log into registry
        run: docker login $DOCKER_REPO_URL -u $DOCKER_USER --password $DOCKER_PASSWORD

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        id: tag_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          SOURCE: release-dash
          WITH_V: true

      - name: Push image
        run: |
          IMAGE_ID=$DOCKER_REPO_URL/$DOCKER_REPOSITORY/$APP_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip "v" prefix from tag name
          VERSION=$(echo ${{ steps.tag_release.outputs.new_tag }} | sed -e 's/^v//')

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $APP_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
